# Generated by Django 4.2.4 on 2024-11-09 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_product_description_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
