# Generated by Django 4.2.4 on 2024-11-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Inasubiri kuthibitishwa'), ('approved', 'Imekamilika'), ('rejected', 'Imekataliwa')], default='pending', max_length=20),
        ),
    ]
