# Generated by Django 4.2.4 on 2024-11-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Inasubiri kuthibitishwa', 'Inasubiri kuthibitishwa'), ('Imekamilika', 'Imekamilika'), ('Imekataliwa', 'Imekataliwa')], default='Inasubiri kuthibitishwa', max_length=200),
        ),
    ]
